# Generated by Django 4.0.6 on 2022-07-24 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='TeamProfile',
        ),
        migrations.AlterModelOptions(
            name='teamprofile',
            options={'verbose_name': 'Team Profile', 'verbose_name_plural': 'Team Profiles'},
        ),
    ]
