# Generated by Django 4.0.6 on 2022-07-26 17:05

from django.db import migrations, models
import hunt.models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_rename_teamgame_puzzlestatus_alter_puzzle_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzlestatus',
            old_name='endgame_time',
            new_name='puzzle_finished_time',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='endgame_key',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='location',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='location_clue',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='penalty_key',
        ),
        migrations.RemoveField(
            model_name='puzzlestatus',
            name='game_finished',
        ),
        migrations.RemoveField(
            model_name='puzzlestatus',
            name='game_finished_time',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='pdf',
            field=models.FileField(null=True, upload_to=hunt.models.user_directory_path),
        ),
    ]
